apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-chart-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deaamoflih/argocd-starboard.git
    path: grafana/helm-chart
    targetRevision: main
    helm:
     valueFiles:
      - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true