apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hillioo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deaamoflih/argocd-starboard.git
    path: grafana/helmo
    targetRevision: sync
    helm:
     valueFiles:
      - values-prod.yaml
     releaseName: helm-chart-test
  destination:
    server: https://kubernetes.default.svc
    namespace: qs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true