apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temp-helm-argo-app
  namespace: argocd
spec:
  project: p
  source:
    chart: nginx-ingress
    repoURL: https://charts.helm.sh/stable
    targetRevision: 1.41.3
    path: guestbook
    helm:
      releaseName: ghost
      valueFiles:
      - dev.yaml
#      values: |
#        targetNamespaces: app
#        trivy:
#          ignoreUnfixed: true
  destination:
    server: https://kubernetes.default.svc
    namespace: helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true