apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL:  https://github.com/deaamoflih/argocd-starboard.git
    targetRevision: sync
    path: sync/aoa/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
