apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-svc
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - releasename: prod-grafana
          chart: grafana
          helmRepo: https://grafana.github.io/helm-charts
          targetRevision: 6.20.5
#        - releasename: devo
#          chart: grafana
#          helmRepo: https://grafana.github.io/helm-charts
#          targetRevision: 6.26.0 
  template:
    metadata:
      name: '{{releasename}}'
      namespace: prod
    spec:
      project: prod
      source:
        chart: '{{chart}}'
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: '{{targetRevision}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: prod
      syncPolicy: 
       automated:
         prune: true
         selfHeal: false
